apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f awacs-cloud.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: adminserver
  name: adminserver
spec:
  ports:
  - name: "8765"
    port: 8765
    targetPort: 8765
  selector:
    io.kompose.service: adminserver
status:
  loadBalancer: {}
