apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f awacs-cloud-standalone.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: adminserver
  name: adminserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: adminserver
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f awacs-cloud-standalone.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: adminserver
    spec:
      containers:
      - env:
        - name: PORT
          value: "80"
        - name: spring.application.name
          value: adminserver
        - name: spring.cloud.bootstrap.enabled
          value: "true"
        image: adminserver
        imagePullPolicy: ""
        name: adminserver
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
