apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f awacs-cloud-standalone.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: authserver
  name: authserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: authserver
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f awacs-cloud-standalone.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: authserver
    spec:
      containers:
      - env:
        - name: GRPC_PORT
          value: "9345"
        - name: PORT
          value: "80"
        - name: eureka.client.service-url.defaultZone
          value: http://admin:admin@peer1/eureka/
        - name: server.forward-headers-strategy
          value: native
        - name: spring.application.name
          value: authserver
        - name: spring.cloud.config.enabled
          value: "true"
        - name: spring.cloud.config.fail-fast
          value: "true"
        - name: spring.cloud.config.uri
          value: http://config/
        - name: spring.cloud.discovery.enabled
          value: "false"
        - name: spring.cloud.service-registry.auto-registration.enabled
          value: "false"
        - name: spring.profiles.active
          value: prod
        image: authserver
        imagePullPolicy: ""
        name: authserver
        ports:
        - containerPort: 80
        - containerPort: 9345
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
