version: '3.3'
services:
  sqlproxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
    hostname: sqlproxy
    restart: always
    expose:
      - 1433
    command: /cloud_sql_proxy -instances=awacs-dev:asia-south1:awacs-test-db=tcp:0.0.0.0:1433 -credential_file=/secrets/cloudsql/gcp.json
    volumes:
     - ./sqlproxy/gcp.json:/secrets/cloudsql/gcp.json

  config:
    image: gcr.io/awacs-dev/awacs-cloud-config-server:latest
    expose:
      - 80
    environment:
       PORT: 80
       debug: 'false'
       GITHUB_TOKEN: 47be97bfa6719d8069d21fced5a70d99847d90a7
       logging.level.org.springframework.cloud.config: debug
       spring.cloud.config.server.git.uri: https://github.com/girishaiocdawacs/scotch-repo

  authserver:
    image: gcr.io/awacs-dev/awacs-cloud-auth-server:latest
    restart: always
    expose:
     - 80
     - 9345
    links:
      - config
      - sqlproxy
    depends_on:
      - sqlproxy
      - config
    environment:
        PORT: 80
        GRPC_PORT: 9345
        spring.cloud.config.uri: http://config/
        spring.application.name: 'authserver'
        spring.profiles.active: prod
        spring.cloud.config.enabled: 'true'
        spring.jpa.hibernate.ddl-auto: 'none'
        spring.cloud.discovery.enabled: 'false'
        spring.cloud.service-registry.auto-registration.enabled: 'false'
        server.forward-headers-strategy: native
        spring.cloud.config.fail-fast: 'true'
        eureka.client.service-url.defaultZone: http://admin:admin@peer1/eureka/

  otpservice:
    image:  gcr.io/awacs-dev/twilio-connector-service:latest
    restart: always
    expose:
    - 80
    links:
    - config
    - authserver
    depends_on:
    - config
    environment:
      PORT: 80
      spring.cloud.config.uri: http://config/
      awacs_grpc_host: authserver
      grpc.client.__name__.negotiationType: 'PLAINTEXT'
      spring.application.name: 'otpservice'
      spring.profiles.active: prod
      spring.cloud.config.enabled: 'true'
      spring.cloud.discovery.enabled: 'false'
      spring.cloud.service-registry.auto-registration.enabled: 'false'
      server.forward-headers-strategy: native
      spring.cloud.config.fail-fast: 'true'
      eureka.client.service-url.defaultZone: http://admin:admin@peer1/eureka/
      awacs_grpc_host: authserver
      grpc.client.__name__.negotiationType: 'PLAINTEXT'

  nginx:
    build:
      context: awacs-nginx
      dockerfile: Dockerfile.nginx.qa
    container_name: awacs_nginx
    restart: always
    ports:
    - 80:80
    - 443:443
    expose:
    - 80
    - 443
    links:
    - authserver
    - otpservice
    depends_on:
    - config
    - authserver
    - otpservice

networks:
  overlay:
