apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f awacs-cloud-standalone.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: config
  name: config
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: config
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f awacs-cloud-standalone.yml convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: config
    spec:
      containers:
      - env:
        - name: GITHUB_TOKEN
          value: f09139bdf78bf4b98e8a3d950eb106e8fa1443f1
        - name: PORT
          value: "80"
        - name: debug
          value: "false"
        - name: logging.level.org.springframework.cloud.config
          value: debug
        - name: spring.cloud.config.server.git.uri
          value: https://github.com/girishaiocdawacs/scotch-repo
        image: gcr.io/awacs-dev/awacs-cloud-config-server:latest
        imagePullPolicy: ""
        name: config
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
