apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f awacs-cloud-standalone.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mysqldb
  name: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysqldb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f awacs-cloud-standalone.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: mysqldb
    spec:
      containers:
      - args:
        - --default-authentication-plugin=mysql_native_password
        - --explicit-defaults-for-timestamp=ON
        env:
        - name: MYSQL_DATABASE
          value: awacs_cloud
        - name: MYSQL_PASSWORD
          value: devbot
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: MYSQL_USER
          value: devbot
        image: mysql
        imagePullPolicy: ""
        name: mysqldb
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
