apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f awacs-cloud.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f awacs-cloud.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: ""
        name: awacs-nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
          - mountPath: /etc/nginx/zerossl/
            name: nginx-ssl
            readOnly: true
          - mountPath: /etc/nginx/conf.d/
            name: nginx-config
            readOnly: true
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-ssl
        secret:
          secretName: app.awacscloud.tech

status: {}

