apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  externalIPs:
      - 192.168.42.71
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-ssl
        secret:
          secretName: nginx-ssl
      # [START container]    
      containers:
      - name: awacs-nginx
        image: nginx
        args: [
          "-n", "/etc/nginx/custom/nginx.conf",
          "-s", "SERVICE_NAME",
          "--rollout_strategy", "managed",
        ]
      # [END container]
        ports:
          - containerPort: 8080
          - containerPort: 443
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: nginx-ssl
          readOnly: true
        - mountPath: /etc/nginx/custom
          name: nginx-config
          readOnly: true
