apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f awacs-cloud.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: otpservice
  name: otpservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: otpservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f awacs-cloud.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: otpservice
    spec:
      containers:
      - env:
        - name: awacs.cloud.auth-server.check-token
          value: http://authserver:8100/oauth/check_token
        - name: management.endpoint.shutdown.enabled
          value: "false"
        - name: management.endpoints.web.exposure.include
          value: '*'
        - name: management.info.git.mode
          value: full
        - name: management.metrics.export.stackdriver.project-id
          value: awacs-cloud-prod
        - name: management.metrics.export.stackdriver.step
          value: 30s
        - name: spring.boot.admin.client.password
          value: awacs
        - name: spring.boot.admin.client.url
          value: http://adminserver:8765
        - name: spring.boot.admin.client.username
          value: awacs
        image: gcr.io/awacs-cloud-prod/twilio-connector-service:latest
        imagePullPolicy: ""
        name: otpservice
        ports:
        - containerPort: 8200
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f awacs-cloud.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: otpservice
  name: otpservice
spec:
  ports:
  - name: "8200"
    port: 8200
    targetPort: 8200
  selector:
    io.kompose.service: otpservice
status:
  loadBalancer: {}
