apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f awacs-cloud-standalone.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: peer1
  name: peer1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: peer1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f awacs-cloud-standalone.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: peer1
    spec:
      containers:
      - env:
        - name: PORT
          value: "80"
        - name: eureka.client.service-url.defaultZone
          value: http://admin:admin@peer1/eureka/
        - name: spring.application.name
          value: discovery
        - name: spring.cloud.config.enabled
          value: "true"
        - name: spring.cloud.config.uri
          value: http://config/
        - name: spring.cloud.discovery.enabled
          value: "false"
        - name: spring.cloud.service-registry.auto-registration.enabled
          value: "true"
        - name: spring.profiles.active
          value: peer1
        image: peer1
        imagePullPolicy: ""
        name: peer1
        ports:
        - containerPort: 80
        resources: {}
      hostname: peer1
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f awacs-cloud-standalone.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: peer1
  name: peer1
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: peer1
status:
  loadBalancer: {}
