apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f awacs-cloud.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: productservice
  name: productservice
spec:
  ports:
  - name: "8181"
    port: 8181
    targetPort: 8181
  selector:
    io.kompose.service: productservice
status:
  loadBalancer: {}
