apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f awacs-cloud-standalone.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: sqlproxy
  name: sqlproxy
spec:
  ports:
  - name: "1433"
    port: 1433
    targetPort: 1433
  selector:
    io.kompose.service: sqlproxy
status:
  loadBalancer: {}
