apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f awacs-cloud-standalone.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: sqlproxy
  name: sqlproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sqlproxy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f awacs-cloud-standalone.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: sqlproxy
    spec:
      containers:
      - args:
        - /cloud_sql_proxy
        - -instances=awacs-dev:asia-south1:awacs-test-db=tcp:0.0.0.0:1433
        - -credential_file=/secrets/cloudsql/gcp.json
        image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
        imagePullPolicy: ""
        name: sqlproxy
        ports:
        - containerPort: 1433
        resources: {}
      hostname: sqlproxy
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
