name: Minikube Staging

on: [push]

jobs:
  example:
    name: Minikube-Jmeter-Play
    runs-on: ubuntu-latest 
    - name: Run JMeter Tests
      uses: rbhadti94/apache-jmeter-action@master
      with:
        testFilePath: .cockpit/jmeter/play.jmx
        outputReportsFolder: reports/
        args: "--loglevel DEBUG -Jname=production --jmeterlogconf=.cockpit/jmeter/log.conf"
        
