name: JMeter

on: 
  push:
    branches:
      - main
jobs:
  jmeter:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Minikube-Jmeter-Play
       uses: rbhadti94/apache-jmeter-action@master
       with:
         testFilePath: .cockpit/jmeter/play.jmx
         outputReportsFolder: reports/
         args: "--loglevel DEBUG -Jname=production --jmeterlogconf=.cockpit/jmeter/log.conf"
