name: Minikube Staging

on: [push]

jobs:
  example:
    name: Minikube-Kubernetes Spin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@master
        with:
          minikube version: 'v1.15.1'
          kubernetes version: 'v1.19.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Interact with the cluster
        run: |
            kubectl config get-contexts
            kubectl config use-context minikube
            kubectl get all
            kubectl config view
            # known bug
            #kubectl create secret tls app.awacscloud.tech --cert=zerossl/certificate.crt --key=zerossl/private.key

            kubectl apply -f adminer-deployment.yaml
            kubectl apply -f adminer-service.yaml

            kubectl apply -f db-deployment.yaml
            kubectl apply -f db-service.yaml

            kubectl apply -f jms-deployment.yaml
            kubectl apply -f jms-service.yaml

            sleep 20

            kubectl apply -f productservice-deployment.yaml
            kubectl apply -f productservice-service.yaml

            kubectl apply -f socialweb-deployment.yaml
            kubectl apply -f socialweb-service.yaml

            kubectl apply -f adminserver-deployment.yaml
            kubectl apply -f adminserver-service.yaml

            kubectl apply -f authserver-deployment.yaml
            kubectl apply -f authserver-service.yaml

            sleep 20

            kubectl apply -f nginx-deployment.yaml
            kubectl apply -f nginx-service.yaml

            sleep 60;

            # kubectl apply -f multi-app-ingress.yaml
            # kubectl expose service/nginx --port=80 --target-port=8080 --name=nginx-ingress --type=LoadBalancer

            sleep 60
            kubectl get all

            minikube_host=$(minikube service nginx | grep 443 | sed -e 's/.*http/https/g' -e 's/ .*//g')

            echo "Hoping at $(minikube_host)"

            curl -k -X POST \
              ${minikube_host}/authserver/oauth/token \
              -u "spring-security-oauth2-read-client:spring-security-oauth2-read-client-password1234" \
              -F grant_type=password \
              -F username=admin \
              -F password=admin1234 \
              -F client_id=spring-security-oauth2-read-client | json_pp

            # minikube service nginx
