name: Minikube Staging

on: [push]

jobs:
  example:
    name: Minikube-Kubernetes Spin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@master
        with:
          minikube version: 'v1.15.1'
          kubernetes version: 'v1.19.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Interact with the cluster
        run: |
            kubectl config get-contexts
            kubectl config use-context minikube
            kubectl config view
            ./minikube_qa.sh
            
            sleep 10;
            kubectl get all

            # minikube_host=$(minikube service nginx | grep 443 | sed -e 's/.*http/https/g' -e 's/ .*//g')
            # minikube_host=$(kubectl get services nginx --output jsonpath={.status.loadBalancer.ingress[0].ip})
            # echo "Hoping at $minikube_host"

            #curl -m 30 -k -X POST \
            #  https://192.168.42.71/authserver/oauth/token \
            #  -u "neo:neo" \
            #  -F grant_type=password \
            #  -F username=admin \
            #  -F password=admin1234 \
            #  -F client_id=neo | json_pp
            #
            #echo "Implicit and client credentials call"
            #curl -m 30 -k -X POST \
            #   https://192.168.42.71/authserver/oauth/token \
            #  -u "spring-security-oauth2-read-write-client:spring-security-oauth2-read-write-client-password1234*" \
            #  -F grant_type=client_credentials | json_pp
            

            # minikube service nginx
