name: Newman Run

on:
  push:
    branches:
    - main
jobs:
  qa:
    runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@master
  #    - uses: matt-ball/newman-action@master
  #      with:
  #       collection: .cockpit/playground.postman_collection.json
  #      environment: .cockpit/qa.awacscloud.tech.postman_environment.json
  #       insecure: true
  #       reporters: cli
  #       color: auto
    steps:
     - name: Checkout
       uses: actions/checkout@master
     - uses: actions/setup-node@v1 #this installs node and npm for us
       with:
         node-version: '15.x'
     - uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
       with:
         path: ~/.npm
         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
         restore-keys: |
             ${{ runner.os }}-node-
     - name: Play
       run: |
           npm install
           npm install -g newman
           
           echo "playing tests"
           newman run \
           -e .cockpit/qa.awacscloud.tech.postman_environment.json \
           .cockpit/playground.postman_collection.json \
           --insecure --verbose --delay-request 100 --reporters cli,json --reporter-json-export outputfile.json
            echo " --------------------- "
            cat  outputfile.json
            echo " --------------------- "
           
