name: Newman Run
on:
  schedule:
    - cron:  '0 */8 * * *' # every 8 hour
  push:
    branches:
    - main
jobs:
  qa:
    runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@master
  #    - uses: matt-ball/newman-action@master
  #      with:
  #       collection: .cockpit/playground.postman_collection.json
  #      environment: .cockpit/qa.awacscloud.tech.postman_environment.json
  #       insecure: true
  #       reporters: cli
  #       color: auto
    steps:
     - name: Checkout
       uses: actions/checkout@master
     - uses: actions/setup-node@v1 #this installs node and npm for us
       with:
         node-version: '15.x'
     - uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
       with:
         path: ~/.npm
         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
         restore-keys: |
             ${{ runner.os }}-node-
     - name: Play
       run: |
           npm install
           npm install -g newman

           echo "playing qa tests"
           newman run \
           -e .cockpit/qa.awacscloud.tech.postman_environment.json \
           .cockpit/playground.postman_collection.json \
           --insecure --verbose -n 100 --timeout-request 5000 --delay-request 100 --reporters cli,json --reporter-json-export outputfile.json

           # echo "playing production tests"
           # newman run \
           # -e .cockpit/app.awacscloud.tech.postman_environment.json \
           # .cockpit/playground.postman_collection.json \
           # --insecure --verbose -n 100 --timeout-request 8000 --delay-request 250 --reporters cli,json --reporter-json-export outputfile-prod.json
           
     - name:  oauth2 curls (qa and production)
       run: | 
           echo "Sample OAuth2 Curls"
           echo "------------ QA -----------------"
           echo "------------ grant_type=password --------"
           curl -kvSs -X POST \
              https://qa.awacscloud.tech/authserver/oauth/token \
              -u "morpheus:morpheus" \
              -F grant_type=password \
              -F username=admin \
              -F password=admin1234 \
              -F client_id=morpheus  | json_pp

           echo "------------ QA -----------------"
           echo "------------ grant_type=client_credentials --------"
           curl -kvsS -X POST \
              https://qa.awacscloud.tech/authserver/oauth/token \
              -u "trinity:trinity" \
              -F grant_type=client_credentials | json_pp


           #echo "------------ PRODUCTION -----------------"
           #echo "------------ grant_type=password --------"
           #curl -kvSs -X POST \
           #   https://app.awacscloud.tech/authserver/oauth/token \
           #   -u "trinity:trinity" \
           #   -F grant_type=password \
           #   -F username=admin \
           #   -F password=admin1234 \
           #   -F client_id=trinity  | json_pp

           # echo "------------ PRODUCTION -----------------"
           # echo "------------ grant_type=client_credentials --------"
           # curl -kvsS -X POST \
           #   https://app.awacscloud.tech/authserver/oauth/token \
           #   -u "spring-security-oauth2-read-client:spring-security-oauth2-read-client-password1234" \
           #   -F grant_type=client_credentials | json_pp
