name: Newman Run

on:
  push:
    branches:
    - main
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
         collection: .cockpit/playground.postman_collection.json
         environment: .cockpit/qa.awacscloud.tech.postman_environment.json
         iterationCount: 4
         insecure: true
         reporters: cli
         bail: true
         insecureFileRead: true
         timeout: Infinity
         timeoutRequest: Infinity
         timeoutScript: Infinity
         delayRequest: 0
         ignoreRedirects: false
         suppressExitCode: false
         color: auto
