name: SSL Certificate Check
on:
  schedule:
    - cron:  '0 */4 * * *' # every 4 hour
  push:
    branches:
    - main
jobs:
  certificate:
    runs-on: ubuntu-latest
    steps:
    - name: Check SSL
      uses: padurean/https-certificate-expiry-health-check-action@v1.0.0
      with:
        url: https://qa.awacscloud.tech|https://app.awacscloud.tech
        check-cert: yes
        max-cert-days-left: 95
        max-attempts: 1
